# Populates your CD repo for flux or argo deployment of traefik

name: CD Build - Traefik

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: 'A GitHub Environment to pull action secrets from'
        required: true
        default: 'cset'
        type: string
      RG:
        description: 'The Resource Group where your resources are deployed'
        required: true
        type: string
      ACRNAME:
        description: 'The Name of the ACR resource'
        required: true
        type: string
      AKVNAME:
        description: 'The Name of the AKV resource'
        required: true
        type: string
      MINAME:
        description: 'The Name of the Managed Identity for traefik to access secrets in the AKV'
        required: true
        type: string


    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

env:
  event_sha: +refs/pull/${{ github.event.issue.number }}/merge

permissions:
      id-token: write
      contents: write

jobs:
  App_Init:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    env:
      RG: "${{ inputs.RG }}"
      ACRNAME: "${{ inputs.ACRNAME}}"
      AKVNAME: "${{ inputs.AKVNAME}}"
      MINAME: "${{ inputs.MINAME}}"

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Job parameter inspection
        run: |
          echo "RG is ${{ inputs.RG }}"
          echo "ACR name is ${{ inputs.ACRNAME }}"
          echo "AKV name is ${{ inputs.AKVNAME }}"
          echo "MI name is ${{ inputs.MINAME }}"

      - name: Azure Login
        uses: Azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: list ACR images
        run: |
          az acr lsit -g $RG

      - name: Push to a Azure Container Registry (ACR)
        run: |
          az acr import --source docker.io/library/traefik:v2.5.3 -n ${{ inputs.ACRNAME }} --force

      - name: Pull identity information
        run: |
          echo "TRAEFIK_USER_ASSIGNED_IDENTITY_RESOURCE_ID=$(az identity show -n $MINAME -g $RG --query id -o tsv)" >> $GITHUB_ENV
          echo "TRAEFIK_USER_ASSIGNED_IDENTITY_CLIENT_ID=$(az identity show -n $MINAME -g $RG --query clientId -o tsv)" >> $GITHUB_ENV
          echo "TRAEFIK_USER_ASSIGNED_IDENTITY_RESOURCE_ID= ${{ env.TRAEFIK_USER_ASSIGNED_IDENTITY_RESOURCE_ID }}"
          echo "TRAEFIK_USER_ASSIGNED_IDENTITY_CLIENT_ID= ${{ env.TRAEFIK_USER_ASSIGNED_IDENTITY_CLIENT_ID }}"

      - name: Create Working Directory
        run: |
          mkdir tmpworking
          echo "TMPWORKDIR=$(pwd)/tmpworking" >> $GITHUB_ENV

      - name: Copy Templates to Working Directory
        run: |
          cp  shared-services/templates/a0008/azureidentity.yaml  ${{ env.TMPWORKDIR }}/
          cp  shared-services/templates/a0008/secretproviderclass.yaml ${{ env.TMPWORKDIR }}/
          cp  shared-services/templates/a0008/traefik.yaml  ${{ env.TMPWORKDIR }}/
          ls -al ${{ env.TMPWORKDIR }}

      - name: Dump variables used to populate yaml files
        run: |
          echo "TMPWORKDIR=${{ env.TMPWORKDIR }}"
          echo "TRAEFIK_USER_ASSIGNED_IDENTITY_RESOURCE_ID=${{ env.TRAEFIK_USER_ASSIGNED_IDENTITY_RESOURCE_ID }}"
          echo "TRAEFIK_USER_ASSIGNED_IDENTITY_CLIENT_ID=${{ env.TRAEFIK_USER_ASSIGNED_IDENTITY_CLIENT_ID }}"
          echo "KEYVAULT_NAME_AKS_BASELINE=${{ env.KEYVAULT_NAME_AKS_BASELINE }}"
          echo "TENANTID_AZURERBAC_AKS_BASELINE=${{ env.TENANTID_AZURERBAC_AKS_BASELINE }}"
          echo "ACR_NAME_AKS_BASELINE=${{ env.ACR_NAME_AKS_BASELINE }}"


      - name: Populate variables in yaml files
        run: |
          escaped_var=$( echo ${{ env.TRAEFIK_USER_ASSIGNED_IDENTITY_RESOURCE_ID }} | sed 's;/;\\/;g')
          echo "Escaped TRAEFIK_USER_ASSIGNED_IDENTITY_RESOURCE_ID for sed usage: $escaped_var"          
          sed -i "s/\${TRAEFIK_USER_ASSIGNED_IDENTITY_RESOURCE_ID}/$escaped_var/g" ${{ env.TMPWORKDIR }}/azureidentity.yaml
          sed -i "s/\${TRAEFIK_USER_ASSIGNED_IDENTITY_CLIENT_ID}/${{ env.TRAEFIK_USER_ASSIGNED_IDENTITY_CLIENT_ID }}/g" ${{ env.TMPWORKDIR }}/azureidentity.yaml
          sed -i "s/\${KEYVAULT_NAME_AKS_BASELINE}/${{ inputs.AKVNAME }}/g" ${{ env.TMPWORKDIR }}/secretproviderclass.yaml
          sed -i "s/\${TENANTID_AZURERBAC_AKS_BASELINE}/${{ secrets.AZURE_TENANT_ID }}/g" ${{ env.TMPWORKDIR }}/secretproviderclass.yaml
          sed -i "s/\${ACR_NAME_AKS_BASELINE}/${{ inputs.ACRNAME }}/g" ${{ env.TMPWORKDIR }}/traefik.yaml

      - name: Move yaml files to cluster mainifest directory and remove temp working dir
        run: |
          cp ${{ env.TMPWORKDIR }}/*.yaml shared-services/cluster-manifests/a0008/
          rm -rf ${{ env.TMPWORKDIR }}

      - name: Check AzureIdentity yaml
        run: |
          echo "Traefiks AzureIdentity yaml file:"
          cat shared-services/cluster-manifests/a0008/azureidentity.yaml

      - name: Check SecretProviderClass yaml
        run: |
          echo "Traefiks secretproviderclass yaml file:"
          cat shared-services/cluster-manifests/a0008/secretproviderclass.yaml

      - name: Check Traefiks deployment yaml
        run: |
          echo "Traefiks deployment yaml file:"
          cat shared-services/cluster-manifests/a0008/traefik.yaml

      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          if [[ "$(git status)" != *"nothing to commit"* ]];then
             git add .
             git commit -a -m "Add Traefik manifest files"
          else
             echo "No changes to traefik yaml files, therefore nothing to commit"
          fi

      - name: Dump github ref
        run: |
          echo "Preparing to push files to ${{ github.ref}}"
          echo "Branch is ${{ github.ref_name}}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

