# This workflow demonstrates building and pushing a container image to an Azure Container Registry.
# The workflow then updates the necessary Kubernetes manifest deployment file so a GitOps operator can sync from the manifest file deploying the application to an Azure Kubernetes Service cluster.
# It is split into separate jobs for readability but could be squashed into a single job if that best suits your scenario.

on: 
  workflow_dispatch:
    inputs:
      ResourceGroupName:
        description: 'The Resource Group where your resources are deployed'
        required: true
        default: "gitops-example"
        type: string
      AKSName:
        description: 'The Name of the AKS resource'
        required: true
        default: "mygitopsappaks1"
        type: string
      ACRName:
        description: 'The Name of the ACR resource'
        required: false
        default: "mygitopsappacr1"
        type: string
      AppName:
        description: 'The Name of the Application to deploy'
        required: false
        default: "azure-vote"
        type: string
      Namespace:
        description: 'The Kubernetes Namespace to deploy the Application to'
        default: "default"
        required: false
        type: string
      AppRepo:
        description: 'The GitHub App code repo'
        default: "azure-samples/azure-voting-app-redis"
        required: false
        type: string
      AppRepoRef:
        description: 'The GitHub REF to use when referencing the App code repo'
        default: "129888"
        required: false
        type: string
      AppRepoPath:
        description: 'The directory in the repo containing the Dockerfile'
        default: "./azure-vote"
        required: false
        type: string
      Environment:
        description: 'A GitHub Environment to pull action secrets from'
        required: false
        default: dev
        type: environment  
      Region:
        description: 'Location where the resources need to be deployed'
        required: false
        default: "eastus2"
        type: string

permissions:
      id-token: write
      contents: write

jobs:
  BuildPush:
    runs-on: ubuntu-latest
    environment: ${{ inputs.Environment }}
    steps:
      - name: Get baseline code from repo
        uses: actions/checkout@v2
      
      # Logs into your Azure subscription
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Run Azure PowerShell script to create necessary resources
        id: create-resources
        uses: azure/powershell@v1
        with:
          inlineScript: |
            cd IaC/scripts
            ./createAppInfra.ps1 -ResourceGroupName ${{ inputs.ResourceGroupName }} -ACRName ${{ inputs.ACRName }} -AKSName ${{ inputs.AKSName }} -Location ${{ inputs.Region }}
          azPSVersion: "latest"
      
      - name: Get ACR Password
        id: acr-pwd
        run: |
          ACR_PASSWORD=$(az acr credential show -g ${{ inputs.ResourceGroupName }} -n ${{ inputs.ACRName }} --query passwords[0].value -o tsv)
          echo "::set-output name=password::$ACR_PASSWORD"
          echo "::add-mask::$ACR_PASSWORD"
  
      # Retrieves your Azure Kubernetes Service cluster's kubeconfig file
      - name: Get K8s context
        uses: azure/aks-set-context@v2.0
        with:
          resource-group: ${{ inputs.ResourceGroupName }}
          cluster-name: ${{ inputs.AKSName }}

      # Creates namespace in your Azure Kubernetes Service cluster's if it does not exist
      - name: Create namespace
        run: |
          namespacePresent=`kubectl get namespace | grep ${{ inputs.Namespace }} | wc -l`
          if [ $namespacePresent -eq 0 ]
          then
              echo `kubectl create namespace ${{ inputs.Namespace }}`
          fi

      # Logs into the Azure Container Registry (ACR)
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ inputs.ACRName }}.azurecr.io
          username: ${{ inputs.ACRName }}
          password: ${{ steps.acr-pwd.outputs.password }}
      
      # Get application code from repo
      - name: Get application code from repo
        uses: actions/checkout@main
        with:
          repository: ${{ inputs.AppRepo}}
          ref: ${{ inputs.AppRepoRef}}

      # Builds and Pushes the container image to the Azure Container Registry (ACR)
      - name: Container build and push to a Azure Container Registry (ACR)
        env:
          AppRepoPath: "${{ inputs.AppRepoPath}}"
          AppName: "${{ inputs.AppName }}"
        run: |
          cd $AppRepoPath
          docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t ${{ inputs.ACRName }}.azurecr.io/${{ inputs.AppName }}:${{ github.run_number }} --label dockerfile-path=Dockerfile
          docker push ${{ inputs.ACRName }}.azurecr.io/${{ inputs.AppName }}:${{ github.run_number }}

  Update-K8s-Manifests:
    name: Update K8s Deployment Manifest with Image Version
    needs: BuildPush
    environment: ${{ inputs.Environment }}
    runs-on: ubuntu-latest
    steps:

    # Checks out the baseline repository
    - uses: actions/checkout@v2

    # Logs into your Azure subscription
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    - name: Update image name in manifest file
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $line = Get-Content workloads/azure-vote/front-deployment.yml | Select-String image: | Select-Object -ExpandProperty Line
          $content = Get-Content workloads/azure-vote/front-deployment.yml
          $content | ForEach-Object {$_ -replace $line,"        image: ${{ inputs.ACRName }}.azurecr.io/${{ inputs.AppName }}:${{ github.run_number }}"} | Set-Content workloads/azure-vote/front-deployment.yml
        azPSVersion: "latest"
    
    - name: Commit changes in manifest to repo
      run: | 
        git config user.name "GitHub Actions Bot"
        git config user.email ""
        git add workloads/azure-vote/front-deployment.yml
        git commit -m "Update image version in K8s Deployment manifests file"
        git push origin
